---
title: "Analyse des données des joueurs (expérimentations pilotes)"
output: html_document
---
```{r include = FALSE}
#install.packages("data.table")
#install.packages("ggplot2")

require(data.table)
require(ggplot2)
require(hexbin)
```

```{r echo=FALSE}
sd_succes = 0.1
nb_players = 1000
sd_niveau_players = 0.1
nb_try = 50
diff_start = 0.1

players = rnorm(nb_players,0.0,sd_niveau_players)

hist(players)

proba_succes = function(d,p){
  return (pmax(pmin(((1-d) + players[p]), 1), 0))
}

jouer = function(p_succes, sd_succes){
  res = rnorm(1,p_succes,sd_succes)
  return(res)
}

confiance = function(val){
  #return (quantile(val,c(.05, .5, .95)))
  return (quantile(val,c(.05,.25, .5, .75,.95)))
}

simu = function(diff_delta_succes,diff_delta_failure){
  MRes = matrix(nrow=nb_players,ncol=nb_try)
  xs = 1:nb_try
  for(p in 1:nb_players){
    paramDiff = diff_start
    for(i in xs){
      
      p_success = proba_succes(paramDiff,p)
      
      MRes[p,i] = 1-p_success
      
      res = jouer(p_success,sd_succes)
      
      #dObj = 0
      #for(k in 1:30)
      #  dObj = dObj + jouer(paramDiff,n);
      #dObj = 1-(dObj / 30)
      
      if(res < 0.5) #si il a perdu
        paramDiff = paramDiff - diff_delta_failure# * abs(res-0.5)*6
      else
        paramDiff = paramDiff + diff_delta_succes# * abs(res-0.5)*6
      
      
    }
  }
  
  #DT = data.table (MRes)
  m = apply(MRes,2,mean)
  s = apply(MRes,2,confiance)
  s_d = apply(MRes,2,sd)
  
  xbin <- jitter(rep(1:nb_try, times=1, each=nb_players),1)
  ybin <- as.vector(MRes)
  
  #
  
  DT1 = data.table(x=xs,y=m, down1=s[1,], up1=s[5,], down2=s[2,], up2=s[4,])
  DT2 = data.table(allpx=xbin,allpy=ybin)
  p <- ggplot(NULL) + ylim(0,1)
  p = p + geom_point(data = DT2, aes(allpx,allpy), alpha = 0.2, size = 1.5, shape=1, color="#009E73")
  p = p + geom_errorbar(data = DT1, aes(x=x, ymin=down1, ymax=up1), width=0.5)
  p = p + geom_errorbar(data = DT1,aes(x=x, ymin=down2, ymax=up2), width=0.5) 
  p = p + geom_point(data = DT1, aes(x,y),alpha = 1, size = 3.0, shape = 21, fill="white") 
  p = p + xlab("step")
  p = p + ylab("difficulty")
  
  #png(file = paste(diff_delta_succes,"out.png",sep=""))
  print(p)
  #dev.off()
  
  
  #bin<-hexbin(xbin, as.vector(MRes), xbins=nb_try/2)
 # plot(bin, main="Hexagonal Binning")
  #plot(xbin,as.vector(MRes), main="Hexagonal Binning") 
  
  #plot(jitter(xbin,1),as.vector(MRes), main="PDF Scatterplot Example", col=rgb(0,100,0,10,maxColorValue=255), pch=1)
  #plot(xbin,as.vector(MRes), ylim=c(0, 1), main="PDF Scatterplot Example", col=rgb(0,100,0,10,maxColorValue=255), pch=1)
  
  
  print("n=10 mean et sd")
  print(m[10])
  print(s_d[10])
  
  print("10 derniers mean val et mean sd")
  print(mean(m[10:(nb_try-11)]))
  print(mean(s_d[10:(nb_try-11)]))
}

#pour du 0.5
#simu(0.02,0.02)
simu(0.05,0.05)
#simu(0.1,0.1)

#pour du 0.4
simu(0.05,0.15)

#pour du 0.3
simu(0.03,0.3)

#pour du 0.2
simu(0.015,0.4)

```
